name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.14

author: RobotoRaccoon
main: ${project.groupId}.${project.artifactId}.Main

commands:
  warden:
    description: The base command for the plugin
    usage: /<command>

permissions:
  warden.bypass:
    description: Users who bypass logging
    default: false
    children:
      warden.bypass.books: true
      warden.bypass.items: true
      warden.bypass.ores: true
      warden.bypass.signs: true
  warden.staff:
    description: Users who are alerted
    default: op
    children:
      warden.staff.ores: true
      warden.staff.signs: true
