#=#====================#=#
#=#     BookWarden     #=#
#=#====================#=#
# Logs any edited or signed books directly to console or a log file
books:
  enabled: true
  options:
    write-console: false
    write-file: true
    log-location: false

#=#====================#=#
#=#     OreWarden      #=#
#=#====================#=#
# Logs all ore finds with certain criteria to staff, console, or a log file
# Each key under ores.blocks must be the Bukkit Material name
# Each block must have max/min heights and a radius
# Each key in defaults may be overriden in the block config as well
ores:
  enabled: true
  options:
    write-console: true
    write-file: true
    ignore-creative: true
  defaults:
    location: true
    light-level: true
    worlds:
      - world
      - another_world
  blocks:
    ### The max and min heights for the first four ores are taken from the wiki
    DIAMOND_ORE:
      max-height: 15
      min-height: 1
      radius: 4
      ### Location will remain on even if the default changes
      location: true
      ### Will only log to these worlds, no matter what the defaults are
      worlds:
        - world
        - world_again
    EMERALD_ORE:
      max-height: 32
      min-height: 1
      radius: 3
      ### Overwrite the default value, ignoring light level
      light-level: false
    GOLD_ORE:
      max-height: 33
      min-height: 1
      radius: 4
    IRON_ORE:
      max-height: 67
      min-height: 1
      radius: 4
    ### You can even add your own blocks with whatever conditions you like
    SPONGE:
      max-height: 255
      min-height: 200
      radius: 3

#=#====================#=#
#=#     SignWarden     #=#
#=#====================#=#
# Logs all signs to a log file
# Logs all signs matching a regex from naughty-phrases to staff, console, or a log file
signs:
  enabled: true
  options:
    write-console: true
    write-file: true
    log-location: true
    ignore-case: true
  naughty-phrases:
    - \bf+a+g+([eio]t)?s?\b
    - \bnig+(er|a)s?\b
    - \b(heil )?hitlers?\b
    - (c|k)unts?
    - fuc*k+?(ing|ed|d)?s?
    - \bgay
    - \banal\b
    - \brap(e|ist)s?\b
    - \bco(ck|q)s?\b
    - \bass(s?hat|hole)?s?\b
    - \b(sperm|jizz)\b
    - \bsex\b
    - \bslut(bag|face)?s?\b
    - whore(house)?s?
    - (?:(^| ))i\W?p\b
    - \bpa?edo((ph|f)ile)?s?\b
    - \bnudes\b